version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    # nginx will proxy /api/* to backend:8000

networks:
  default:
    driver: bridge
